ifneq ($(TARGET_NO_TELEPHONY), true)
ifneq ($(TARGET_HAS_QTI_OPTIMIZATIONS), true)
ifeq ($(TARGET_FWK_SUPPORTS_FULL_VALUEADDS),true)
PRODUCT_PACKAGES += \
                 Mms
endif#TARGET_FWK_SUPPORTS_FULL_VALUEADDS
endif#TARGET_HAS_QTI_OPTIMIZATIONS
endif#TARGET_NO_TELEPHONY
