ifneq ($(TARGET_NO_TELEPHONY), true)
ifeq ($(TARGET_FWK_SUPPORTS_FULL_VALUEADDS),true)
ifneq ($(TARGET_1G_DDR_RAM), true)
PRODUCT_PACKAGES += \
                 Mms
endif#TARGET_1G_DDR_RAM
endif#TARGET_FWK_SUPPORTS_FULL_VALUEADDS
endif#TARGET_NO_TELEPHONY
